#!/usr/bin/env python3
"""Turn game/assets/logo.png into src/logo.h for the Switch loading
screen: scaled to WIDTH, composited onto the loader's background (the loader
blits it, so there is no blending), run-length encoded as (count, R, G, B).

    python3 scripts/make-logo.py        # needs Pillow
"""
import os, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
WIDTH = 640
BG = (8, 10, 13)          # src/platform/switch.c: loader background

im = Image.open(os.path.join(ROOT, "game", "assets", "logo.png")).convert("RGBA")
im = im.resize((WIDTH, round(im.height * WIDTH / im.width)), Image.LANCZOS)
bg = Image.new("RGBA", im.size, BG + (255,))
bg.alpha_composite(im)
px = list(bg.convert("RGB").get_flattened_data()) if hasattr(bg, "get_flattened_data") \
    else list(bg.convert("RGB").getdata())
w, h = bg.size

runs = []
i = 0
while i < len(px):
    j = i
    while j + 1 < len(px) and px[j + 1] == px[i] and j + 1 - i < 255:
        j += 1
    runs.append((j - i + 1,) + px[i])
    i = j + 1

out = os.path.join(ROOT, "src", "logo.h")
with open(out, "w") as f:
    f.write("/* Generated by scripts/make-logo.py from game/assets/logo.png"
            ". Do not edit. */\n")
    f.write(f"#define LOGO_W {w}\n#define LOGO_H {h}\n")
    f.write(f"#define LOGO_BG_R {BG[0]}\n#define LOGO_BG_G {BG[1]}\n"
            f"#define LOGO_BG_B {BG[2]}\n")
    f.write("/* runs of (count, r, g, b), row-major from the top */\n")
    f.write(f"static const unsigned char k_logo_rle[{len(runs) * 4}] = {{\n")
    flat = [v for r in runs for v in r]
    for k in range(0, len(flat), 24):
        f.write("    " + ",".join(str(v) for v in flat[k:k + 24]) + ",\n")
    f.write("};\n")
print(f"{out}: {w}x{h}, {len(runs)} runs ({len(runs) * 4} bytes)", file=sys.stderr)
